### ISSUE TITLE
Add concept of event object

### ISSUE THREAD

**Issue by arieljake** [Wolfy87/EventEmitter#91] opened 2015-02-16 17:06 UTC
Right now, EventEmitter's concept of an event is just a string name. When an event is emitted, there is no event object. Simply, all listeners are called and they receive the arguments specified.

If there were an event object involved, then the event could contain data (the arguments) as well as methods like "preventDefault" and "isDefaultPrevented" and a callback that can be fired when all listeners have been called.

Something akin to what the standard browser event emitters dispatch.
https://developer.mozilla.org/en-US/docs/Web/API/Event

In the browser, we can use the native Event class, and if passed as the first argument to emit, we can use event.type to get the string type to dispatch and provide the event as the one argument.

Node doesn't seem to have an Event class, maybe we can polyfill one.

Thoughts?

**Comment by arieljake** [comment] 2015-02-16 17:30
Sorry, didn't elaborate why this would affect EventEmitter and cannot be implemented independent of EventEmitter.

EventEmitter, I believe, would need to be aware of this event object to honor stopImmediatePropogation and the idea of a promise/callback embedded in the event for async event handling.

**Comment by nathggns** [comment] 2015-02-16 21:15
I believe this is way out of scope for this project. It would make the project unnecessarily larger for the majority of use cases in my opinion.

**Comment by arieljake** [comment] 2015-02-16 21:24
What if we simply changed a to b:

a) while (i--)
       response = listener.listener.apply(this, args || []);

b) Q.async(listeners[key]) (from the kriskowal/q lib)

This would enable listeners to return a promise IF they wanted to create a chain of promises that could throw errors.

**Comment by nathggns** [comment] 2015-02-16 21:31
Because promises are slow.

**Comment by Wolfy87** [comment] 2015-02-16 21:42
This is not really like the DOM style event system where in events bubble or propagate, so there is no need for control over that. The event system is entirely flat, fast and simple. This is by design.

Although I like the idea of adding optional hooks for extension by allowing things other than strings as keys, I think it is out of scope too, as @nathggns mentioned. I don't think promises are always slow, they definitely have their place and can help keep your asynchronous JavaScript from trying to attack you.

I like the idea of a more extensible version that allows the consumer control over the system. Something that starts simple and can be composed with almost anything else to solve more complex problems. Why not fork the project and play with it in your own time? I'd be happy to see your findings or link directly to it from here if it proved to be a capable but fundamentally different variant.

**Comment by Wolfy87** [comment] 2015-03-09 14:58
Going to close this since it's a nice idea but out of scope right now. I just want this to remain binding strings to functions. If you want a meta-data object, pass one when you invoke it.

**Closed by Wolfy87** 2015-03-09 14:58 UTC
